repos:
  - repo: local
    hooks: 
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data with TruffleHog.
        entry: bash -c 'trufflehog git file://. --fail --no-update'
        language: system
        stages: ["pre-commit", "pre-push"]